In [1]:
import numpy as np

In [2]:
np.array([1,2,3])

array([1, 2, 3])

In [3]:
a = np.array([1,2,3])
b = np.array([1,3,5])
a + b

array([2, 5, 8])

In [4]:


a = np.zeros([2, 2], dtype = int)
print("\nMatrix a : \n", a)

b = np.zeros(2, dtype = int)
print("Matrix b : \n", b)
  
c = np.zeros([3, 3])
print("\nMatrix c : \n", c)


Matrix a : 
 [[0 0]
 [0 0]]
Matrix b : 
 [0 0]

Matrix c : 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [5]:
import numpy as np

a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])

add_ans = a+b
print(add_ans)

c = np.array([1, 2, 3, 4])
add_ans = a+b+c
print(add_ans)

add_ans = np.add(a, b, c)
print(add_ans)

[  7  77  23 130]
[  8  79  26 134]
[  7  77  23 130]


In [6]:
a = np.arange(20)
print("\n Array is:\n ",a)

print("\n a[-8:17:1] = ",a[-8:17:1])

print("\n a[-8:17:2] = ",a[-8:19:2])


print("\n a[10:] = ",a[10:])


 Array is:
  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

 a[-8:17:1] =  [12 13 14 15 16]

 a[-8:17:2] =  [12 14 16 18]

 a[10:] =  [10 11 12 13 14 15 16 17 18 19]


In [7]:
# --- 1. Create a NumPy Array ---
# Create a 3x3 array of random integers
data = np.random.randint(1, 10, size=(3, 3))
print("Original Array:")
print(data)

Original Array:
[[2 1 1]
 [1 5 9]
 [9 7 2]]


In [8]:
# --- 2. Array Operations (Vectorization) ---
# Add a constant to every element
data_plus_10 = data + 10
print("\nArray + 10:")
print(data_plus_10)


Array + 10:
[[12 11 11]
 [11 15 19]
 [19 17 12]]


In [9]:
# Multiply two arrays element-wise
array_2 = np.array([[1, 0, 1], [0, 1, 0], [1, 0, 1]])
multiplied = data * array_2
print("\nElement-wise Multiplication:")
print(multiplied)


Element-wise Multiplication:
[[2 0 1]
 [0 5 0]
 [9 0 2]]


In [10]:
# --- 3. Statistical Functions ---
print(f"\nMean of all elements: {data.mean():.2f}")
print(f"Sum of elements in each column (axis=0): {data.sum(axis=0)}")


Mean of all elements: 4.11
Sum of elements in each column (axis=0): [12 13 12]
